/**
 * Ambient module declarations for the Soroban contract bindings
 * packages generated by scripts/generate-bindings.sh (vault-client,
 * lending-client, price-oracle-client, zk-verifier-client).
 *
 * These packages don't exist in node_modules until you've deployed
 * the corresponding contract and run that script — without this
 * file, `tsc`/`next build` fails to resolve the dynamic imports in
 * hooks/use*.ts even though those imports are correctly guarded at
 * runtime (see isContractsConfigured() checks). This file's job is
 * purely to satisfy the type checker with a deliberately loose
 * `any`-shaped contract; it does NOT make the packages real.
 *
 * Once you've run scripts/generate-bindings.sh and added the real
 * packages to package.json as local `file:` dependencies, TypeScript
 * will prefer their real, fully-typed declarations over this file
 * automatically (real .d.ts files always take precedence over a
 * manual ambient `declare module`), so this file is safe to leave in
 * place permanently rather than needing to delete it later.
 */

declare module "vault-client" {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const Client: any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const networks: any;
}

declare module "lending-client" {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const Client: any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const networks: any;
}

declare module "price-oracle-client" {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const Client: any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const networks: any;
}

declare module "zk-verifier-client" {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const Client: any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  export const networks: any;
}

/**
 * snarkjs ships no first-party TypeScript types (confirmed: it's a
 * plain JS package). This is intentionally loose — see useZkProof.ts
 * for the one call site that uses this, with its own detailed risk
 * documentation about the proof byte-encoding step downstream of it.
 */
declare module "snarkjs" {
  export const groth16: {
    fullProve: (
      input: Record<string, unknown>,
      wasmPath: string,
      zkeyPath: string
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    ) => Promise<{ proof: any; publicSignals: string[] }>;
  };
}
