// AUTO-GENERATED placeholder — regenerated by:
//   scripts/build_circuit.sh -> scripts/export_vkey_rust.js
//
// Do NOT deploy with these zero-filled bytes. They exist only so
// `cargo build` succeeds before the Circom trusted setup has run.
// After running build_circuit.sh against circuits/portfolio_threshold.circom,
// this file is overwritten with the real verifying key (uncompressed
// BLS12-381 point encodings, G1_SERIALIZED_SIZE=96 / G2_SERIALIZED_SIZE=192
// bytes per point, matching soroban_sdk::crypto::bls12_381::{G1Affine,G2Affine}).

use soroban_sdk::{crypto::bls12_381::{G1Affine, G2Affine}, Env};
use crate::VerificationKey;

// Raw uncompressed point bytes (ark-serialize `serialize_uncompressed` layout).
const VK_ALPHA: [u8; 96] = [0u8; 96];
const VK_BETA: [u8; 192] = [0u8; 192];
const VK_GAMMA: [u8; 192] = [0u8; 192];
const VK_DELTA: [u8; 192] = [0u8; 192];

// IC[0] = constant term, IC[1..] correspond to public signals
// [threshold, min_assets, owner_commit] in that order.
const VK_IC_0: [u8; 96] = [0u8; 96];
const VK_IC_1: [u8; 96] = [0u8; 96];
const VK_IC_2: [u8; 96] = [0u8; 96];
const VK_IC_3: [u8; 96] = [0u8; 96];

pub fn verifying_key(env: &Env) -> VerificationKey {
    VerificationKey {
        alpha: G1Affine::from_array(env, &VK_ALPHA),
        beta: G2Affine::from_array(env, &VK_BETA),
        gamma: G2Affine::from_array(env, &VK_GAMMA),
        delta: G2Affine::from_array(env, &VK_DELTA),
        ic: soroban_sdk::Vec::from_array(
            env,
            [
                G1Affine::from_array(env, &VK_IC_0),
                G1Affine::from_array(env, &VK_IC_1),
                G1Affine::from_array(env, &VK_IC_2),
                G1Affine::from_array(env, &VK_IC_3),
            ],
        ),
    }
}
